config/routes.rb
Rails.application.routes.draw do

  get 'table/index'
  root to: 'table#index', as: 'table'

  resources :calendar_events do
    put 'ajax_update', on: :member
  end

  devise_for :users, :controllers => { :omniauth_callbacks => 'users/omniauth_callbacks' }

  resources :users do
    collection do
      put'update_and_import'
      put'update_and_export'
    end
  end
  resources :google do
    collection do
      get :redirect
      get :callback
      get :import_events
      get :export_events
    end
  end

end

app/models/calendar_event.rb
class CalendarEvent < ActiveRecord::Base
  belongs_to :user

  validates_presence_of :start_date, :end_date, :title

  validate :end_date_is_after_start_date, :check_all_day


  private

  def check_all_day
    if !all_day
      # если не all_day но несколько дней
      if(end_date.to_date - start_date.to_date) > 0
        errors.add(:all_day, 'Что-то тут не так')
      end
      # если не all_day и меньше получаса (все криво)
      if 1799 >= (end_date.to_time - start_date.to_time)
        errors.add(:end_date, 'Длительность должна быть не менее получаса')
      end
    end
  end

  def end_date_is_after_start_date
    return if end_date.blank? || start_date.blank?

    if end_date < start_date
      errors.add(:start_date, 'Start_date должен быть раньше чем End_date')
    end
  end

end

app/controllers/calendar_events_controller.rb
class CalendarEventsController < ApplicationController
  before_action :set_calendar_event, only: [:ajax_update, :show, :edit, :update, :destroy]
  respond_to :html, :json

  # GET /calendar_events
  # GET /calendar_events.json
  def index
    @calendar_events = CalendarEvent.all
  end

  # GET /calendar_events/1
  # GET /calendar_events/1.json
  def show
  end

  # GET /calendar_events/new
  def new
    @user_id = current_user.id
    @calendar_event = CalendarEvent.new(params[:calendar_event].nil? ? nil : calendar_event_params )
    respond_modal_with @calendar_event
  end

  # GET /calendar_events/1/edit
  def edit
    respond_modal_with @calendar_event
  end

  def create
    @calendar_event = CalendarEvent.new(calendar_event_params)
    # @calendar_event.uid = SecureRandom.hex
    @calendar_event.save
    respond_modal_with @calendar_event, :location => :back
  end

  def ajax_update
    if request.xhr?
      if @calendar_event.update(calendar_event_params)
        render json: {status: 'success', message: 'Event saved!'}
      else
        render json: {status: 'failure', message: 'Event save error!'}
      end
    end
  end

  # PATCH/PUT /calendar_events/1
  # PATCH/PUT /calendar_events/1.json
  def update
    @calendar_event.update(calendar_event_params)
    respond_modal_with @calendar_event, :location => :back
  end

  # DELETE /calendar_events/1
  # DELETE /calendar_events/1.json
  def destroy
    @calendar_event.destroy
    respond_modal_with @calendar_event, :location => :back
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_calendar_event
    @user_id = current_user.id
    @calendar_event = CalendarEvent.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def calendar_event_params
    params.require(:calendar_event).permit(:uid, :title, :all_day, :start_date, :end_date, :user_id)
  end
end

app/views/calendar_events/_form.html.erb
<%= simple_form_for(@calendar_event, remote: request.xhr?, html: {data: {modal: true}, class: 'form-horizontal'}) do |f| %>
    <% if @calendar_event.errors.any? %>
        <div id="error_explanation" class="alert alert-danger">
          <ul>
            <% @calendar_event.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <%= f.input :title, input_html: {class: 'form-control'} %>

    <% if @calendar_event.all_day.nil? || !@calendar_event.all_day %>
        <%= f.input :all_day %>
    <% else %>
        <%= f.input :all_day, as: :hidden %>
    <% end %>

    <%= f.input :start_date, as: :string, input_html: {class: 'form-control', id: 'start_date_picker',
                                                       value: @calendar_event.start_date ? @calendar_event.start_date.strftime('%d.%m.%Y %H:%M') : '' }%>

    <%= f.input :end_date, as: :string, input_html: {class: 'form-control datetimepicker', id: 'end_date_picker',
                                                     value: @calendar_event.end_date ? @calendar_event.end_date.strftime('%d.%m.%Y %H:%M') : '' }%>

    <%= f.input :user_id, as: :hidden, input_html: {value: @user_id } %>

    <div class="actions">
      <%= f.submit class: 'btn btn-primary' %>
      <% if params[:action] == 'edit' %>
          <%= link_to 'Destroy', @calendar_event, class: 'btn btn-danger', method: :delete, data: {confirm: 'Are you sure?'} %>
      <% end %>
    </div>
<% end %>

<script>
  init_datetime_picker();
</script>

app/views/calendar_events/edit.html.erb
<%= render 'form' %>

app/views/calendar_events/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Calendar Events</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>All day</th>
      <th>Start date</th>
      <th>End date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @calendar_events.each do |calendar_event| %>
      <tr>
        <td><%= calendar_event.title %></td>
        <td><%= calendar_event.all_day %></td>
        <td><%= calendar_event.start_date %></td>
        <td><%= calendar_event.end_date %></td>
        <td><%= link_to 'Show', calendar_event %></td>
        <td><%= link_to 'Edit', edit_calendar_event_path(calendar_event) %></td>
        <td><%= link_to 'Destroy', calendar_event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Calendar event', new_calendar_event_path %>

app/views/calendar_events/new.html.erb
<%= render 'form' %>

app/views/calendar_events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @calendar_event.title %>
</p>

<p>
  <strong>All day:</strong>
  <%= @calendar_event.all_day %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @calendar_event.start_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @calendar_event.end_date %>
</p>

<%= link_to 'Edit', edit_calendar_event_path(@calendar_event) %> |
<%= link_to 'Back', calendar_events_path %>