config/routes.rb
Rails.application.routes.draw do

  get 'table/index'
  root to: 'table#index', as: 'table'

  resources :calendar_events do
    put 'ajax_update', on: :member
  end

  devise_for :users, :controllers => { :omniauth_callbacks => 'users/omniauth_callbacks' }

  resources :users do
    collection do
      put'update_and_import'
      put'update_and_export'
    end
  end
  resources :google do
    collection do
      get :redirect
      get :callback
      get :import_events
      get :export_events
    end
  end

end

app/views/calendar_templates/_day_calendar.html.erb
<div class="diary day_calendar">
  <div class="calendar-head">
    <div class="left-panel">
      <%= link_to t('diary.previous', default: 'Пред.'), calendar.prev_page, class: 'btn btn-default' %>
      <%= link_to t('diary.next', default: 'След.'), calendar.next_page, class: 'btn btn-default' %>
      <%= link_to t('diary.today', default: 'Сегодня'), calendar.today, class: 'btn btn-default' %>
    </div>
    <span class="date-title"><%= start_date.strftime('%B %d, %Y') %></span>
    <div class="right-panel">
      <div class="btn-group">
        <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Action <span class="caret"></span>
        </button>
        <ul class="dropdown-menu">
          <li><%= link_to new_calendar_event_path, data: {modal: true} do %>
                Добавить событие <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
            <% end %></li>
          <% if user %>
              <li data-toggle="modal" data-target="#google-import">
                <a>Google import <span class="glyphicon glyphicon-import" aria-hidden="true"></span></a></li>
              <li data-toggle="modal" data-target="#google-export">
                <a>Google export <span class="glyphicon glyphicon-export" aria-hidden="true"></span></a></li>
          <% end %>
        </ul>
      </div>
      <div class="btn-group">
        <%= link_to t('diary.today', default: 'День'), calendar.to_calendar('day_calendar'), class: 'btn btn-default' %>
        <%= link_to t('diary.today', default: 'Неделя'), calendar.to_calendar('week_calendar'), class: 'btn btn-default' %>
        <%= link_to t('diary.today', default: 'Месяц'), calendar.to_calendar('month_calendar'), class: 'btn btn-default' %>
      </div>
    </div>
  </div>

  <%= render partial: 'calendar_templates/google_modal', locals: {user: user} if user %>

  <table class="table day_table droppable_table">
    <thead>
    <tr class="table-header">
      <td class="hours">Hours</td>
      <%= content_tag :td, class: calendar.td_classes_for(start_date) << 'date', data: {date: start_date.to_date, all_day: true, modal: true}  do %>
          <h4><%= start_date.strftime('%A') %></h4>
      <% end %>
    </tr>
    </thead>
  </table>

  <table class="table day_table">
    <tbody>
    <tr>
      <td style="border: none">
        <div style="position: relative">
          <div class="day-event-content">
            <table class="table day_table">
              <tbody>
              <tr>
                <td class="hours"></td>
                <%= content_tag :td, class: calendar.td_classes_for(start_date) do %>
                <% end %>
              </tr>
              </tbody>
            </table>
          </div>

          <div class="all_day_row">
            <table class="all_day_table">
              <tr>
                <td class="hours">AllDay</td>
                <td>
                  <div class="all_day_scrollable for_day">
                    <table>
                      <tbody class="all_day_content day_calendar">
                      <% (sorted_events.select { |key| key === start_date }).each do |pair| %>
                          <% pair.fetch(1).each do |event| %>
                              <% next if !event.all_day %>
                              <% event_data = 'data-id=' + event.id.to_s + ' data-all-day=' + event.all_day.to_s + ' data-start-date=' +
                                  event.start_date.to_datetime.to_s + ' data-end-date=' + event.end_date.to_datetime.to_s  %>
                              <tr>
                                <td>
                                  <div <%= event_data%> class="event week_event"><%= event.title %></div>
                                </td>
                              </tr>
                          <% end %>
                      <% end %>
                      </tbody>
                    </table>
                  </div>
                </td>
              </tr>
            </table>
          </div>

          <div class="day-scrollable">
            <div style="position: relative">
              <table class="day_table_row">
                <% (0 .. 84600).step(1800) do |hour| %>
                    <% time = Time.at(hour).utc %>
                    <tr>
                      <td class="hours"><%= time.strftime('%H:%M') %></td>
                      <td></td>
                    </tr>
                <% end %>
              </table>

              <div class="day-event-content">
                <table class="table event_hour_table">
                  <tbody>
                  <tr>
                    <td class="hours"></td>
                    <%= render partial: 'calendar_templates/hour_events_template', locals: {sorted_events: sorted_events, day: start_date} %>
                  </tr>
                  </tbody>
                </table>
              </div>
            </div>
          </div>


        </div>
      </td>
    </tr>
    </tbody>
  </table>
</div>

app/views/calendar_templates/_day_events_template.html.erb
 <% events.each do |event| %>
        <% start_date = event.start_date.to_date %>
        <% end_date = event.end_date.to_date %>
        <% start_included = date_range.include?(start_date) %>
        <% end_included = date_range.include?(end_date) %>
        <% resizable_class = event.all_day ? 'event-resizable' : '' %>
        <% event_data = 'data-id=' + event.id.to_s + ' data-all-day=' + event.all_day.to_s + ' data-start-date=' +
                    event.start_date.to_datetime.to_s + ' data-end-date=' + event.end_date.to_datetime.to_s  %>
        <% if calendarType == 'month' %>
          <% width = 124 %>
        <% elsif calendarType == 'week' %>
          <% width = 117%>
        <% end %>
        <tr>
          <% if date_range.to_a.include?(start_date) %>
              <% (start_date.cwday - 1).times do %>
                  <td></td>
              <% end %>
          <% end %>

          <!--Если начало и конец на одной неделе-->
          <% if start_included && end_included %>
              <% colpan =  end_date.cwday - start_date.cwday + 1 %>
                <!--Для длительных событый которые занимают всю неделю+ -->
          <% elsif key.include?(date_range.first) && key.include?(date_range.last) %>
              <% colpan =  7 %>
              <% resizable_class = ''%>
                <!--Если только начало на этой неделе-->
          <% elsif start_included %>
              <% max = 8 - start_date.cwday %>
              <% current = (end_date - start_date).to_i %>
              <% colpan = current > max ? max : current %>
              <% resizable_class = ''%>
                <!--Если только конец на этой неделе-->
          <% elsif end_included %>
              <% colpan = end_date.cwday %>
          <% end %>
          <td colspan="<%= colpan %>" style="width: <%=  (colpan*width).to_s + 'px'%>">
            <div <%= event_data %> class="event week_event ">
              <div class="event_title">
                <%= event.title %>
              </div>
              <% if !resizable_class.blank? %>
                  <div style="float: right" class="<%= resizable_class %>">
                    <span class="glyphicon glyphicon-forward" aria-hidden="true"></span>
                  </div>
              <% end %>
            </div>
          </td>

          <% if end_included%>
              <% (7 - end_date.cwday).times do %>
                  <td></td>
              <% end %>
          <% end %>
        </tr>
 <% end %>

app/views/calendar_templates/_events_template.html.erb
<% (sorted_events.select { |key| !(key.to_a & date_range.to_a).empty? }).each do |pair| %>
    <% key = pair.fetch(0) %>
    <% events = pair.fetch(1) %>

    <% events.each do |event| %>
        <% start_date = event.start_date.to_date %>
        <% end_date = event.end_date.to_date %>
        <% start_included = date_range.include?(start_date) %>
        <% end_included = date_range.include?(end_date) %>
        <tr>
          <% if date_range.to_a.include?(start_date) %>
              <% (start_date.cwday - 1).times do %>
                  <td></td>
              <% end %>
          <% end %>

          <!--Если начало и конец на одной неделе-->
          <% if start_included && end_included %>
              <td colspan="<%= end_date.cwday - start_date.cwday + 1 %>">
                <!--Для длительных событый которые занимают всю неделю+ -->
          <% elsif key.include?(date_range.first) && key.include?(date_range.last) %>
              <td colspan="7">
                <!--Если только начало на этой неделе-->
          <% elsif start_included %>
              <% max = 8 - start_date.cwday %>
              <% current = (end_date - start_date).to_i %>
              <td colspan="<%= current > max ? max : current %>">
                <!--Если только конец на этой неделе-->
          <% elsif end_included %>
              <td colspan="<%= end_date.cwday %>">
          <% end %>
          <div class="event"><%= event.title %></div>
          </td>
        </tr>
    <% end %>
<% end %>

app/views/calendar_templates/_google_modal.html.erb
<!-- Modal -->
<div class="modal fade" id="google-import" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Import</h4>
      </div>
      <%= simple_form_for user, url: update_and_import_users_path, html: {method: :put} do |f| %>
          <div class="modal-body">
            <%= f.input :client_id, input_html: {class: 'form-control'} %>
            <%= f.input :client_secret, input_html: {class: 'form-control'} %>
            <%= f.input :calendar_id, input_html: {class: 'form-control'} %>
          </div>
          <div class="modal-footer" style="text-align: left">
            <%= f.submit 'Update & Import', class: 'btn btn-primary' %>
            <%= link_to 'Import', {controller: :google, action: :import_events}, class: 'btn btn-success' %>
            <div class="btn btn-default" data-dismiss="modal">Close</div>
          </div>
      <% end %>
    </div>
  </div>
</div>


<div class="modal fade" id="google-export" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Export</h4>
      </div>
      <%= simple_form_for user, url: update_and_export_users_path, html: {method: :put} do |f| %>
          <div class="modal-body">
            <%= f.input :client_id, input_html: {class: 'form-control'} %>
            <%= f.input :client_secret, input_html: {class: 'form-control'} %>
            <%= f.input :calendar_id, input_html: {class: 'form-control'} %>
          </div>
          <div class="modal-footer" style="text-align: left">
            <%= f.submit 'Update & Export', class: 'btn btn-primary' %>
            <%= link_to 'Export', {controller: :google, action: :export_events}, class: 'btn btn-success' %>
            <div class="btn btn-default" data-dismiss="modal">Close</div>
          </div>
      <% end %>
    </div>
  </div>
</div>

app/views/calendar_templates/_hour_events_template.html.erb
<% all_events = sorted_events.select { |key| key === day } %>
<td class="hour-date" data-date="<%= day.to_date %>" data-all-day="<%= false %>" style="position: relative">
  <% if !all_events.empty? %>
      <!--TODO СДЕЛАТЬ РАСЧЕТЫ ЧТОБЫ ЭВЕНТЫ АДАПТИВНО РАСПОЛАГАЛИСЬ(КАК В FULLCALENDAR НАПРИМЕР)-->
      <% all_events.each do |pair| %>
          <% day_events = pair.fetch(1).select { |event| !event.all_day } %>
          <% day_events.each_with_index do |event, index| %>
              <% event_data = 'data-id=' + event.id.to_s + ' data-all-day=' + event.all_day.to_s + ' data-start-date=' +
                  event.start_date.to_datetime.to_s + ' data-end-date=' + event.end_date.to_datetime.to_s %>
              <% pos = ((index*2)) %>
              <% position = index.odd? ? 'right: ' + pos.to_s + 'px' : 'right: auto' %>
              <% width = (100/day_events.count).to_s + '%' %>
              <% top_position = (event.start_date.hour + (event.start_date.strftime('%M').to_i)/60.0)*100 %>

              <% if event.end_date.day - event.start_date.day == 0 %>
                  <% event_height = ((event.end_date.hour - event.start_date.hour) +
                      (event.end_date.strftime('%M').to_i - event.start_date.strftime('%M').to_i)/60.0)*100 %>
              <% else %>
                  <% event_height = (24 -(event.start_date.hour + (event.start_date.strftime('%M').to_i)/60.0))*100 %>
              <% end %>

              <div <%= event_data %> class="event hour-event" style="position: absolute;
                  height: <%= event_height %>px; top:<%= top_position %>px;
                  <%= position %>;width: <%= width %>; overflow: hidden ">
                <div class="event_title">
                  <%= event.title %>
                </div>
                <div <%= event_data %> class="to_all_day" title="Drag to green date for switch to all_day">
                  <span class="glyphicon glyphicon-eject" aria-hidden="true"></span>
                </div>
                <div class="timer">
                    <span class="start_date">
                    <%= event.start_date.strftime('%H:%M') %> -
                    </span>
                    <span class="end_date">
                    <%= event.end_date.strftime('%H:%M') %>
                    </span>
                </div>
              </div>
          <% end %>
      <% end %>
  <% end %>
</td>

app/views/calendar_templates/_month_calendar.html.erb
<div class="diary month_calendar">
  <div class="calendar-head">
    <div class="left-panel">
      <%= link_to t('diary.previous', default: 'Пред.'), calendar.prev_page, class: 'btn btn-default' %>
      <%= link_to t('diary.next', default: 'След.'), calendar.next_page, class: 'btn btn-default' %>
      <%= link_to t('diary.today', default: 'Сегодня'), calendar.today, class: 'btn btn-default' %>
    </div>
    <span class="date-title"><%= start_date.strftime('%B %Y') %></span>
    <div class="right-panel">
      <div class="btn-group">
        <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Action <span class="caret"></span>
        </button>
        <ul class="dropdown-menu">
          <li><%= link_to new_calendar_event_path, data: {modal: true} do %>
                Добавить событие <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
            <% end %></li>
          <% if user %>
              <li data-toggle="modal" data-target="#google-import">
                <a>Google import <span class="glyphicon glyphicon-import" aria-hidden="true"></span></a></li>
              <li data-toggle="modal" data-target="#google-export">
                <a>Google export <span class="glyphicon glyphicon-export" aria-hidden="true"></span></a></li>
          <% end %>
        </ul>
      </div>
      <div class="btn-group">
        <%= link_to t('diary.today', default: 'День'), calendar.to_calendar('day_calendar'), class: 'btn btn-default' %>
        <%= link_to t('diary.today', default: 'Неделя'), calendar.to_calendar('week_calendar'), class: 'btn btn-default' %>
        <%= link_to t('diary.today', default: 'Месяц'), calendar.to_calendar('month_calendar'), class: 'btn btn-default' %>
      </div>
    </div>
  </div>

  <%= render partial: 'calendar_templates/google_modal', locals: {user: user} if user %>

  <table class="table month_table">
    <thead>
    <tr class="table-header">
      <td style="border: none">
        <div>
          <table>
            <thead>
            <% date_range.slice(0, 7).each do |day| %>
                <td><%= t('date.abbr_day_names')[day.wday] %></td>
            <% end %>
            </thead>
          </table>
        </div>
      </td>
    </tr>
    </thead>

    <tbody>
    <tr>
      <td style="border: none">
        <div class="drag-container" style="position: relative">
          <% date_range.each_slice(7) do |week| %>
              <div style="position: relative">
                <table class="month_table_row">
                  <tr>
                    <% week.each do |day| %>
                        <%= content_tag :td, class: calendar.td_classes_for(day) do %>
                        <% end %>
                    <% end %>
                  </tr>
                </table>
                <div class="event-content-container">
                  <table class="month_table_row droppable_table">
                    <thead>
                    <tr>
                      <% week.each do |day| %>
                          <%= content_tag :th, class: calendar.td_classes_for(day) << 'date', data: {date: day.to_date, all_day: true, modal: true} do %>
                              <% block.call day.strftime('%d') %>
                          <% end %>
                      <% end %>
                    </tr>
                    </thead>
                    <tbody class="month_table_body">
                    <% if (sorted_events.select { |key| !(key.to_a & week.to_a).empty? }).empty? %>
                        <tr>
                          <% week.each do |day| %>
                              <%= content_tag :td, class: calendar.td_classes_for(day) do %>
                              <% end %>
                          <% end %>
                        </tr>
                    <% else %>
                        <% (sorted_events.select { |key| !(key.to_a & week.to_a).empty? }).each do |pair| %>
                            <% key = pair.fetch(0) %>
                            <% events = pair.fetch(1) %>

                            <%= render partial: 'calendar_templates/day_events_template', locals: {key: key, events: events, date_range: week, calendarType: 'month'} %>
                        <% end %>
                    <% end %>
                    </tbody>
                  </table>
                </div>
              </div>
          <% end %>
        </div>
      </td>
    </tr>
    </tbody>
  </table>
</div>

app/views/calendar_templates/_week_calendar.html.erb
<div class="diary week_calendar">
  <div class="calendar-head">
    <div class="left-panel">
      <%= link_to t('diary.previous', default: 'Пред.'), calendar.prev_page, class: 'btn btn-default' %>
      <%= link_to t('diary.next', default: 'След.'), calendar.next_page, class: 'btn btn-default' %>
      <%= link_to t('diary.today', default: 'Сегодня'), calendar.today, class: 'btn btn-default' %>
    </div>
    <span class="date-title"><%= start_date.strftime('%B %Y') %></span>
    <div class="right-panel">
      <div class="btn-group">
        <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Action <span class="caret"></span>
        </button>
        <ul class="dropdown-menu">
          <li><%= link_to new_calendar_event_path, data: {modal: true} do %>
                Добавить событие <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
            <% end %></li>
          <% if user %>
          <li data-toggle="modal" data-target="#google-import">
            <a>Google import <span class="glyphicon glyphicon-import" aria-hidden="true"></span></a></li>
          <li data-toggle="modal" data-target="#google-export">
            <a>Google export <span class="glyphicon glyphicon-export" aria-hidden="true"></span></a></li>
          <% end %>
        </ul>
      </div>
      <div class="btn-group">
        <%= link_to t('diary.today', default: 'День'), calendar.to_calendar('day_calendar'), class: 'btn btn-default' %>
        <%= link_to t('diary.today', default: 'Неделя'), calendar.to_calendar('week_calendar'), class: 'btn btn-default' %>
        <%= link_to t('diary.today', default: 'Месяц'), calendar.to_calendar('month_calendar'), class: 'btn btn-default' %>
      </div>
    </div>
  </div>

  <%= render partial: 'calendar_templates/google_modal', locals: {user: user}  %>

  <table class="table week_table droppable_table">
    <thead>
    <tr class="table-header">
      <td class="hours">Hours</td>
      <% date_range.slice(0, 7).each do |day| %>
          <%= content_tag :td, class: calendar.td_classes_for(day) << 'date', data: {date: day.to_date, all_day: true, modal: true} do %>
              <%= day.strftime('%A %d') %>
          <% end %>
      <% end %>
    </tr>
    </thead>
  </table>


  <table class="table week_table">
    <tbody>
    <tr>
      <td style="border: none">
        <div style="position: relative">
          <div class="week-event-content">
            <table class="table week_table">
              <tbody>
              <tr>
                <td class="hours"></td>
                <% date_range.slice(0, 7).each do |day| %>
                    <%= content_tag :td, class: calendar.td_classes_for(day) do %>
                    <% end %>
                <% end %>
              </tr>
              </tbody>
            </table>
          </div>

          <div class="all_day_row">
            <table class="all_day_table">
              <tr>
                <td class="hours">AllDay</td>
                <td>
                  <div class="all_day_scrollable">
                    <table>
                      <tbody class="all_day_content">
                      <% (sorted_events.select { |key| !(key.to_a & date_range.to_a).empty? }).each do |pair| %>
                          <% key = pair.fetch(0) %>
                          <% events = pair.fetch(1).select { |event| event.all_day } %>
                          <%= render partial: 'calendar_templates/day_events_template', locals: {key: key, events: events, date_range: date_range, calendarType: 'week'} %>
                      <% end %>
                      </tbody>
                    </table>
                  </div>
                </td>
              </tr>
            </table>
          </div>

          <div class="day-scrollable">
            <div style="position: relative">
              <!--TODO ПОНЯТЬ КАК СДЕЛАТЬ ЭТУ СЕТКУ МЕЖДУ week-event-content и events(z-index)  -->
              <!--<div style="position: relative; z-index: 2">-->
                <table class="week_table_row">
                  <% (0 .. 84600).step(1800).with_index do |hour| %>
                      <% time = Time.at(hour).utc %>
                      <tr>
                        <td class="hours"><%= time.strftime('%H:%M') %></td>
                        <% date_range.slice(0, 7).each do |day| %>
                          <td></td>
                        <% end %>
                      </tr>
                  <% end %>
                </table>


              <div class="week-event-content">
                <table class="table event_hour_table">
                  <tbody>
                  <tr>
                    <td class="hours"></td>
                    <% date_range.slice(0, 7).each do |day| %>
                        <%= render partial: 'calendar_templates/hour_events_template', locals: {sorted_events: sorted_events, day: day} %>
                    <% end %>
                  </tr>
                  </tbody>
                </table>
              </div>
            </div>
          </div>

        </div>
      </td>

    </tr>
    </tbody>
  </table>

</div>